version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: root_db
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  nocodb:
    image: nocodb/nocodb
    restart: always
    ports:
      - 8080:8080
    volumes:
      - nc_data:/usr/app/data
    environment:
      NC_DB: pg://host.docker.internal:5432?u=postgres&p=postgres&d=root_db

volumes:
  postgres_data:
    external: false
  nc_data:
    external: false